In [1]:
#McCulloh Pitt model for AND model
import numpy as np

def McAnd(x,w,t):
    net = np.dot(x,w)
    if net>t:
        output = 1
    else:
        output = 0
    return output

x0 = np.array([0,0,1])
x1 = np.array([0,1,1])
x2 = np.array([1,0,1])
x3 = np.array([1,1,1])
w = np.array([1,1,-1])

t = 0
ans1 = McAnd(x0,w,t)
print (x0, "value", ans1)
ans2 = McAnd(x1,w,t)
print (x1, "value", ans2)
ans3 = McAnd(x2,w,t)
print (x2, "value", ans3)
ans4 = McAnd(x3,w,t)
print (x3, "value", ans4)

[0 0 1] value 0
[0 1 1] value 0
[1 0 1] value 0
[1 1 1] value 1


In [2]:
## MP-OR
import numpy as np
def McOR(x,w,t):
    net = np.dot(x,w)
    #Using Bipolar Activation
    if net>t:
        output = 1
    else:
        output = -1
    return output

#inputs and weights
x0 = np.array([0,0,1])
x1 = np.array([0,1,1])
x2 = np.array([1,0,1])
x3 = np.array([1,1,1])
w = np.array([2,2,-1])

t = 0 #threshold


#verifying the output
ans1 = McOR(x0,w,t)
print (x0, "value", ans1)
ans2 = McOR(x1,w,t)
print (x1, "value", ans2)
ans3 = McOR(x2,w,t)
print (x2, "value", ans3)
ans4 = McOR(x3,w,t)
print (x3, "value", ans4)

[0 0 1] value -1
[0 1 1] value 1
[1 0 1] value 1
[1 1 1] value 1


In [3]:
## MP-NOT
import numpy as np
def McNot(x,w,t):
    #Using Sigmoidal Activation
    net = np.dot(x,w);
    out = 1/(1+np.exp(-0.1*net));
    if out>t:
        output = 1
    else:
        output = 0
    return output

#inputs and weights
x0 = np.array([0,1])
x1 = np.array([1,1])
w = np.array([-1,1])


t = 0.5 #threshold

#verifying the output
ans1 = McNot(x0,w,t)
print (x0, "value", ans1)
ans2 = McNot(x1,w,t)
print (x1, "value", ans2)

[0 1] value 1
[1 1] value 0
